import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon/mani_logo.png" type="image/png" />
        <title>Portfolio</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
